import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarDemo } from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "StoreSome",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={inter.className}>
        <SidebarDemo/>
        {children}</body>
    </html>
  );
}
